version: '3.8'

networks:
  pf-net:
    name: pf-net
    driver: bridge
    ipam:
      driver: default
     

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: helloworld
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: always
    user: postgres 
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    volumes:
      - ./Migrations:/migrations
    networks:
      - pf-net
    depends_on:
      - db
    entrypoint: ["/bin/sh", "-c"]
    command: >
      'migrate -database "postgres://postgres:helloworld@db:5432/postgres?sslmode=disable" -path /migrations force 1 && yes | migrate -path /migrations -database "postgres://postgres:helloworld@db:5432/postgres?sslmode=disable" down &&
      migrate -path /migrations -database "postgres://postgres:helloworld@db:5432/postgres?sslmode=disable" up'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "4000:4000"
    depends_on:
      - migrate
      - db
    networks:
      - pf-net
    volumes:
      - ./:/apiServer
      

 
volumes:
  db-data: